[tool.black]
exclude = '''
(
  /(
    gateware/logic
   | gateware/lowlevel
   | gateware/linien_module.py
   | linien-server/linien_server/csrmap.py
   )/
)
'''

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
plt_dirname = "tests/plots"

# don't complain about plt_dirname
filterwarnings = "ignore::pytest.PytestConfigWarning"

markers = """slow : marks tests as slow (deselect with '-m "not slow"')"""
