name: Upload Packages to TestPyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Build linien-common
        working-directory: linien-common
        run: python -m build

      - name: Build linien-server
        working-directory: linien-server
        run: python -m build

      - name: Build linien-client
        working-directory: linien-client
        run: python -m build

      - name: Build linien-gui
        working-directory: linien-gui
        run: python -m build

      - name: Publish linien-common to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: linien-common/dist/
          password: ${{ secrets.TEST_PYPI_API_TOKEN_COMMON }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish linien-server to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: linien-server/dist/
          password: ${{ secrets.TEST_PYPI_API_TOKEN_SERVER }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish linien-client to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: linien-client/dist/
          password: ${{ secrets.TEST_PYPI_API_TOKEN_CLIENT }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish linien-gui to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: linien-gui/dist/
          password: ${{ secrets.TEST_PYPI_API_TOKEN_GUI }}
          repository_url: https://test.pypi.org/legacy/
